routes:
  - prefix: 10.0.1.3
    mask: 255.255.255.255
    fwd_list:
      - fwd: GigabitEthernet2
        metric: 1

  - prefix: 10.0.0.4
    mask: 255.255.255.255
    fwd_list:
      - fwd: GigabitEthernet2
        metric: 2

  - prefix: 10.0.1.4
    mask: 255.255.255.255
    fwd_list:
      - fwd: GigabitEthernet3
        metric: 30

  - prefix: 172.30.1.1
    mask: 255.255.255.255
    fwd_list:
      - fwd: 64.102.247.254
        metric: 1

  - prefix: 0.0.0.0
    mask: 0.0.0.0
    fwd_list:
      - fwd: 64.102.247.129
        metric: 1